### ISSUE TITLE
SimplePicker doesn’t work correctly - the last available item can not be picked

### ISSUE THREAD

**Issue by andrakula** [Alfresco/Aikau#1012]
SimplePicker didn't work with Alfresco 5.0.3 by my local environment (the last available item can not be picked). 
And then I used a textarea of Sandpit to create a simple SimplePicker (see a screenshot). It was the same problem. Which Version of Aikau uses Aikau Sandpit?

![bildschirmfoto 2016-04-21 um 13 37 29](https://cloud.githubusercontent.com/assets/7724548/14707914/893b2514-07c7-11e6-8e4f-6f7dfde35c2f.png)

**This is a simple example:**

`[ { "name" : "alfresco/forms/controls/SimplePicker", "config" : { "label" : "Pick Some items", "description" : "This is a simple picker with some hard-coded data", "name" : "hardcoded", "reorderable" : true, "currentData" : { "items" : [ { "name" : "One" }, { "name" : "Two" }, { "name" : "Three" } ] } } } ]`

**Comment by draperd** [comment]
OK, first... I closed the other #1011, you could just re-open that issue - don't open a new one. However, now that you have described the problem slightly better ... i.e. that it is "the last remaining option after having picked all the others" rather than "the last option displayed in the list of available options" I have been able to reproduce the problem. 

The Sandpit is always running on the last release of Aikau, so at the time of writing it is on 1.0.64. There is no SimplePicker example on it yet - we are not necessarily going to provide examples of all existing widgets, but as we create new widgets we will add them to the Sandpit.

If you'd like to provide a SimplePicker example for the Sandpit then you can do so via a pull request. I'll raise a JIRA issue for the problem that you've found and it will be addressed in our next sprint.

**Comment by draperd** [comment]
I've raised https://issues.alfresco.com/jira/browse/AKU-946 to capture this problem. As a bug it will be automatically included in our next sprint so you can expect a fix in the 1.0.66 release.

**Comment by draperd** [comment]
I've started investigating this issue and I've found that it's not that you can't select the last item, it's just that you have to ensure that the mouse is correctly showing a pointer (indicating that the select action is available). It definitely isn't working as it should be (i.e. if the mouse is over the select icon then it should work, and it isn't). I've attached a video to https://issues.alfresco.com/jira/browse/AKU-946 that demonstrates this.

I'd be interested to know if you are experiencing the same scenario - i.e. that you have to ensure the mouse cursor is a pointer in order for the select to work.

**Comment by draperd** [comment]
We have a fix available - it's pending review and merge but this should be resolved in the 1.0.66 release that will be available next week.

**Comment by draperd** [comment]
This has been fixed in the 1.0.66 release which is now available.

**Comment by andrakula** [comment]
Great! Thank you!
