### ISSUE TITLE
Question Related to tutorial 1

### ISSUE THREAD

**Issue by jzhangCat** [Alfresco/Aikau#1072]
I completed the Tutorial 1 - Getting Started and notice items in the "Actions" does nothing except the "Download" option. Is that expected? If so, how to enable the functionality of other options like "Delete" and "Move to..."?

**Comment by draperd** [comment]
When requesting data directly via the Repository (e.g. using `rawData=true`) then default actions will be generated based on the node type and the permissions that the user has on the node. The permissions should vary depending upon what nodes you're looking at. I'm surprised that you were only just seeing "Download" though - were these just on folders or were they also on documents? Also, were you logging in as "admin" or a regular user - if a regular user, what permissions does the user have for the documents that you were looking at? Finally, what version of Aikau were you using?

**Comment by jzhangCat** [comment]
All actions are rendered, but not usable except "Download".
Log in as admin, Alfresco Share v5.1.f, Alfresco Community v5.1.0.

**Comment by draperd** [comment]
OK... the issue here is that the actions are handled by services. The point of the first tutorial chapter is to just get a basic Document Library up and running. The tutorial does describe further down about adding services to support some actions, but for a full Document Library experience you're better off using the Document Library lib files that are shipped in Aikau JARs...

Take a look at [this blog post](https://www.alfresco.com/blogs/developer/2016/04/12/aikau-1-0-63-support-for-versioned-library-imports/) for background information on ensuring that you're using versioned imports and then [this blog post](https://www.alfresco.com/blogs/developer/2016/05/23/adding-the-aikau-document-library-as-a-site-page-in-share/) for another example of using the lib files.

Use the `getDocumentLibraryServices` function to get all the services required for providing action support.

**Comment by draperd** [comment]
As there have  been no further updates on this issue, I'm closing it.
