### ISSUE TITLE
ManageAspectsService error when configured with a single aspect

### ISSUE THREAD

**Issue by vincent-kali** [Alfresco/Aikau#1077]
When configuring 'alfresco/services/actions/ManageAspectsService' with a single aspect as available/addable/removable, this aspect is correctly displayed in the left pane of aspectPicker (available/addable) but when trying to add it nothing appends.
When ManageAspectsService' is configured with multiple aspects as available/addable/removable, I can add/remove aspect, except that I can't add more than one aspect.....

I'm using v 1.0.64 (it seems that no change as been applied since this version on ManageAspectsService')

-> to reproduce: (part of page js controller)

model.jsonModel = {
   services: [
	"alfresco/services/DocumentService",
	"alfresco/services/UploadService",
	"alfresco/services/DialogService",
	"alfresco/services/OptionsService",
	{
		name: "alfresco/services/actions/ManageAspectsService",
		config: {			
			availableAspects: ["mycm:myAspect1"],
			addableAspects: ["mycm:myAspect1"],	
			removableAspects: ["mycm:myAspect1"]	
// with this config, you can add aspect one aspect only (if an aspect is already added, you can't the second aspect to the node)
//			availableAspects:  ["mycm:myAspect1", "mycm:myAspect2"],
//			addableAspects: ["mycm:myAspect1", "mycm:myAspect2"],
//			removableAspects: ["mycm:myAspect1", "mycm:myAspect2"],
    },

	........

ManagerAspectService is called from a alfresco/renderers/PublishAction widget in a list cell, like this:

	name: "alfresco/lists/views/layouts/Cell",
	config: {
		additionalCssClasses: "smallpad",
		widgets: [
			{
			name: "alfresco/renderers/PublishAction",
			config: {
				altText: "Manage document aspects",
				iconClass: "edit-16",
				publishTopic: "ALF_MANAGE_ASPECTS_REQUEST",
				publishPayloadType: "PROCESS",
				useCurrentItemAsPayload: false,
				publishPayloadModifiers: ["processCurrentItemTokens","convertNodeRefToUrl"],
				publishPayload: {
					node: {
						nodeRef: "{node.nodeRef}",
					},
				displayName: "{node.properties.cm:name}"
				}
			}
		}
.......

**Comment by draperd** [comment]
I'm wondering if this is actually the same problem that was reported and fixed in Aikau 1.0.66 under https://issues.alfresco.com/jira/browse/AKU-946 / #1012. 

The Manage Aspects picker uses the Simple Picker and there was a problem with the "Loading..." element preventing selection of items. What you're describing would certainly fit this pattern. It would definitely be worth you testing against a more recent version of Aikau. The latest version at the time of writing is 1.0.68 but we are aware of a corruption in the layout of the Manage Aspects dialog introduced in 1.0.68 that has been fixed in https://issues.alfresco.com/jira/browse/AKU-977 and will be resolved in the 1.0.69 release.

I'd be very grateful if you could try 1.0.66 onwards. We do have unit tests for the Manage Aspects action that are not failing, but not that have a single addable aspect.

**Comment by draperd** [comment]
I've just made an update to our ManageAspects test page to only have a single available/addable/removable aspect and it is working fine. I do suspect that the problem you're dealing with was fixed under #1012. Look for the changing mouse pointer as you hover over the "add" icon to make sure that the pointer event is being picked up.

**Comment by vincent-kali** [comment]
Ok, I'll test with 1.0.66 and let you know.
Thanks.

**Comment by vincent-kali** [comment]
I confirm that 1.0.66 fix both issues. I can now 
- add aspect when a single available/addable/removable aspect is configured
- add more that one aspect if multiple available/addable/removable aspect are configured

But the layout corruption seems to appear in 1.0.66 as well, I'll wait for 1.0.69 to test this further.
Thanks

**Comment by draperd** [comment]
1.0.69 is now available, I'm happy with the current rendering of the Manage Aspects dialog, but if you still feel there are any layout corruptions then you can re-open or raise a new issue.
