### ISSUE TITLE
PubSub not working correctly for DialogService in all cases

### ISSUE THREAD

**Issue by stevenokennedy** [Alfresco/Aikau#1161]
When using the dialog service to launch a form, the subscription for the _formConfirmationTopic (ALF_CREATE_FORM_DIALOG_MIXIN_CONFIRMATION_TOPIC by defalt) is set up to be not "global", however the event published from clicking the form confirmation button (OK button) does not seem to be published globally.  As a result the topic configured as the formSubmissionTopic in the Dialog widget never gets published. 

This may only happen in the case of a pubsub scope being set higher up the widget hierarchy (e.g. at the top of jsonModel), it is unclear, but definitely in this case the subscription is registered as <PubSubScope><UniqueDialogId>ALF_CREATE_FORM_DIALOG_MIXIN_CONFIRMATION_TOPIC 

but the topic that gets published on clicking the OK button on the forms is 
<UniqueDialogId>ALF_CREATE_FORM_DIALOG_MIXIN_CONFIRMATION_TOPIC 

This could potentially be fixed by a change in the DialogService, inside the onCreateFormRequest function to make the subscription for the topic global:

var confirmationHandle = this.alfSubscribe(subcriptionTopic, lang.hitch(this, this.onFormDialogConfirmation), **true**);

Because the dialog service uses its own unique id for each generated form/dialog, using the global option here doesn't cause pollution and still allows events to be caught by the correct dialog only.

**Comment by draperd** [comment]
I think that this is a failing in our JSDoc rather than in the capabilities of the DialogService. There are in fact other attributes that can be provided which do not appear to be currently included in the [DialogService documentation](http://dev.alfresco.com/resource/docs/aikau-jsdoc/DialogService.html) or the [event documentation](http://dev.alfresco.com/resource/docs/aikau-jsdoc/DialogService.html#event:ALF_CREATE_FORM_DIALOG_REQUEST).

There are in fact additional attributes that can be passed in the request (see [line 777](http://dev.alfresco.com/resource/docs/aikau-jsdoc/DialogService.js.html#line777) in the 1.0.77 version of the JSDoc)
* formSubmissionGlobal
* formSubmissionScope

We also have a comprehensive [unit test](https://github.com/Alfresco/Aikau/blob/dbe4f7286d4cbd1d7a46a3da924104076ee90306/aikau/src/test/resources/alfresco/services/DialogServiceTest.js) that covers all sorts of permutations of using the service on [this page](https://github.com/Alfresco/Aikau/blob/dbe4f7286d4cbd1d7a46a3da924104076ee90306/aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/services/DialogService.get.js).

In fact the DialogService is used across many more of the unit tests.

One of the key considerations of Aikau is to be backwards compatible, so it would not be possible to make the change you're requesting without potentially breaking existing implementations using Aikau.

However, hopefully you're able to get it working with this additional information. I will however create a pull request to update the documentation.

**Comment by draperd** [comment]
Actually, just re-reading your description... and I think I might have misinterpreted on the first reading. However, I'm still not sure that a change is necessary... even if the DialogService is scoped then the scope should be inherited so that subscriptions and publications?

Perhaps you could provide a concrete model where a failure occurs so that we can use it in our test page in order to verify the problem exists, find a solution and then prevent future regressions?

**Comment by draperd** [comment]
There's been no update on this issue for a couple of weeks now, so I'm going to close it. Please feel free to re-open with the requested information if you feel that it is still a problem.
