### ISSUE TITLE
Hardcoded uses of topics.SORT_LIST despite AlfList allowing configuration of sortRequestTopic

### ISSUE THREAD

**Issue by AFaust** [Alfresco/Aikau#1352]
The AlfList module allows configuration of the sortRequestTopic so it may differ from the default value inherited from the _AlfDocumentListTopicMixin, and the SortOrderToggle module even allows configuration of the subscriptionTopic and oNConfig/offConfig constructs (which include a publishTopic). Despite this, several uses in HeaderCell and AlfSortablePaginatedList are hard-coded to use the topics.SORT_LIST constant, which renders all of the configurability moot.

As I may have mentioned sometime in the past: I consider the use of any topics.XY constant problematic when it is used for anything other than setting the default value of a configuration property. If there are topics that really need to be internal then these should not be configurable in any module. If at least one module allows configuration of a topic that uses a constant as a default value, that contant should never be used for hard-coding subscription or publication calls.

**Comment by draperd** [comment]
I actually think that my implementation of the topic mixin classes was a poor choice and have been trying to move away from it. The benefit of the topics constants is primarily for documentation but also to avoid string duplication.

I don't disagree that topics should be configurable on widgets, but I see no need to work through the entire suite of widgets and add that configuration on the off-chance that someone may one day need it.

Therefore I'm quite happy for you to submit a pull request adding a configuration attribute for the topics which defaults to the constant value so that backwards compatibility is retained, but reconfiguration is possible.
