### ISSUE TITLE
In "alfresco/renderers/Indicators"  is not included "alfresco/renderers/Property"

### ISSUE THREAD

**Issue by troncador** [Alfresco/Aikau#1376]
In "alfresco/renderers/Indicators" the function use getRenderedProperty and it doesn't exist  in 'this'.
```javascript
  postMixInProperties: function alfresco_renderers_Indicators__postMixInProperties() {
    var property = this.currentItem && this.propertyToRender && this.currentItem.node.properties[this.propertyToRender];
     // this.getRenderedProperty doesn't exist !!
     this.renderedValue = (property && this.getRenderedProperty(property)) || ""; 
     this._currentIndicators = this.normaliseIndicators(this.currentItem);
 },
```
I think "alfresco/renderers/Property" should be included in the dependencies

**Comment by draperd** [comment]
I think that you're correct here. However, the current situation is that Aikau has been de-prioritized and as such we are not making any more releases other than to hotfix customer raised issues on features included in Alfresco Share. It's interesting that the unit tests didn't pick up on this failure so the widget must be functional to some extent. If however, this issue is directly impacting you then it can easily be resolved by extending the `alfresco/renderers/Indicators` widget and simply adding in the additional dependency, e.g.

``` JAVASCRIPT
define(["dojo/_base/declare", 
        "aikau/renderers/Indicators",
        "alfresco/renderers/Property"], 
        function(declare, Indicators, Property) {

   return declare([Indicators, Property], {})
})
```

Therefore at the present time this issue will not be fixed.
