### ISSUE TITLE
Easy way to add custom actions

### ISSUE THREAD

**Issue by rderooij** [Alfresco/Aikau#303]
Hi,

So far, I really like the Aikau framework. Only what I am missing is an easy way to add custom actions (in document list). Like the ActionFormProcessor of Share. Actions makes it very easy to add additional business logic to you're solution. You can add an onActionFormDialog and you can create an action that will send all additional parameters. Is there a way to do this in Aikau? I noticed the onActionSimpleRepoAction in the code. Only this is limited. It provides only the action name and actionedUponNoderef (used for workflow). 

Do you support this already? If not, can you provide a sample that illustrates sending the payload information as params to a backend API (to initiate the action)? I don't mind to build the backend myself (that is not the challenging part). But a sample would be great!

Thank you for you're time.

Rick

**Comment by draperd** [comment]
Hi Rick,

Thanks for the feedback... the general area of the Document Library and in particular action handling is the biggest challenge that we have at the moment because we want to be able to support the existing Share XML configured actions as well as being able to define custom actions and be able to fall back to sensible defaults based on Node metadata.

At the moment we only support a subset of the actions available on Share today (and are in the process of converting the others - although this isn't a high priority item at the moment). We do however have a item on our backlog for the next sprint (https://issues.alfresco.com/jira/browse/AKU-361) to support adding custom actions into the standard actions generated from Share Document Library configuration.

In the long term I hope that we'll be able to move away from the Share Document Library approach because it's actually considerably harder add new actions or customize existing ones using that approach.

So we will get there in time, but at the moment it's not completely ready... once we have AKU-361 complete then we'll probably have a complete model of how we want to take actions forwards, if not complete action support.

If there are particular actions that you need support for then please let us know so that we can prioritize them.

Regards,
Dave

**Comment by rderooij** [comment]
Hi Dave,

Thank you for your response. I will wait for the next release.

Rick

**Comment by draperd** [comment]
I've made some updates to this so that it'll now be possible to combine the standard actions (e.g. those defined in the share-documentlibrary-config.xml) with additional actions defined by either the "customActions" and/or the "widgetsForActions" attributes.

The difference between these two attributes is that the former is just basic configuration for a menu item, whereas the latter is where we define actions as full AMD modules to allow them to be defined in page models so that additional dependencies can be handled. This approach will also lend itself to the ability to configure actions in drag-and-drop page creation/customization tooling in the future (if ever decide to implement some).

You should probably compare both approaches to see what meets your requirements best.

**Comment by draperd** [comment]
The fix is now available in the 1.0.23 release that is available.
