### ISSUE TITLE
CRUDForm available via dialog service

### ISSUE THREAD

**Issue by DarkStar1** [Alfresco/Aikau#358]
It's nice to be able to call the form dialog via the form service, but it would be nicer if the crud form is also exposed via this service, perhaps via a payload attribute of the ALF_CREATE_FORM_DIALOG_REQUEST topic.

**Comment by draperd** [comment]
It's been so long since I wrote or did anything with that widget that I'd forgotten it already exists and had to look it up! :)

We haven't had actually used this widget in a production scenario yet, so it would be useful if you could provide some further feedback on any other issues with it or any further improvements that could be made. Just having a cursory glance at the code I can see that we can make some general improvements and being able to create a CrudForm rather than a regular Form through the DialogService would be a nice feature. I'll raise a JIRA feature for us to work on this.

In the meantime, if you could provide us a sample use case for how you'd like to use this it would be very useful.

Thanks.

**Comment by DarkStar1** [comment]
I am Aikau-ifying some forms in share right now. One of the things I am working on is a custom form for another object in alfresco similar to a user, it strikes me that I would also want to expose the same creation from for user creation and update in the admin tools section, through the same tool as they both share 80% of the same form widgets.

**Comment by draperd** [comment]
I've raised this as https://issues.alfresco.com/jira/browse/AKU-402 in JIRA. We'll try to get this done in a future sprint soon. Please feel free to add additional comments on it or add further information here.

**Comment by draperd** [comment]
I'm just reviewing the open issues - are you still interested in us making this change, to be perfectly honest I think that this widget is something I'd quite like to deprecate for removal as it doesn't fit with our current thinking. As far as I'm aware, you're the only person that has expressed an interest in using it. If you want to keep this issue open then I'll try and bump it up the backlog and see if we can slot it in somewhere should we get any slack.

**Comment by draperd** [comment]
No update on this, so I'm going to close this issue and deprecate the module.
