### ISSUE TITLE
Search Page Appearance

### ISSUE THREAD

**Issue by anooj-monu** [Alfresco/Aikau#372]
Hi Dave,

I have made some changes in search page . All of sudden i see a change in my page which looks similar to Toggle developer view (check in the below screenshot) without apply debug mode. Ca you just help me out with this issue. 

Thanks 
Anooj

**Comment by anooj-monu** [comment]
![page error screenshot](https://cloud.githubusercontent.com/assets/12935725/8587882/861b0126-2620-11e5-822d-d79918e34ddc.JPG)

**Comment by draperd** [comment]
It's nothing to do with the developer view... the issue here is that it looks like your CSS is missing. This can happen if you've providing a CSS file that cannot be compiled by the LESS pre-processor in Share. Check the server stdout logs to see if any compilation errors being generated or go back over recent CSS changes and see if there is anything that will cause LESS compilation to fail.

**Comment by anooj-monu** [comment]
Thanks 
issue solved 
problem was with the css .
