### ISSUE TITLE
Override core styles

### ISSUE THREAD

**Issue by DarkStar1** [Alfresco/Aikau#379]
What would be the best way to override the core css so as to bring in sweeping changes (like change fonts for instance) to all widgets?

**Comment by MartinDoyleUK** [comment]
I'd suggest having a read of [this blog post](http://blogs.alfresco.com/wp/developer/2015/05/19/share-header-colour-customization/), as it explains how you can override the LESS variables that we use in Aikau. The caveat is that we are in the process of analysing our usage of these variables, with a view to making them more logical and with greater usage, so there are currently many examples of hard-coded values. Please give it a go and if you get any problems then let us know so that we can prioritise fixes where most needed.

**Comment by MartinDoyleUK** [comment]
@DarkStar1 is that enough information for you? Should I close this issue, or are you still having problems implementing your desired changes?

**Comment by MartinDoyleUK** [comment]
Closing this issue. Please let us know if you need any further help with this.
