### ISSUE TITLE
Tutorial 18 - Cannot get document preview

### ISSUE THREAD

**Issue by boneill** [Alfresco/Aikau#695]
Hi David,

I have followed tutorial 18 but cannot get it to show a page with a preview.  The "No Document Details Provided" error message appears if I call the page without the store, id etc.( ie http://localhost:8090/aikau-sample/page/ap/ws/document) but if I call the same page passing in the store id etc, ie http://localhost:8090/aikau-sample/page/ap/ws/document/workspace/SpacesStore/5fa74ad3-9b5b-461b-9df5-de407f1f4fe7  then it just shows a blank page.  Do you have the home.js and document.js so I can have a look at where I am going wrong.

Brian

**Comment by draperd** [comment]
Hi Brian,

Thanks for raising this issue... what version of Aikau are you using?

The reason I ask is that some issues were reported with the previewer (towards the end of #617) and we made some fixed in the 1.0.42 release.

The key part about tutorial 18 is to make sure that you've got your URI template configuration set up correctly - if you're seeing a blank page it suggests that this might be related to the problem. Changing the UR template configuration will require a restart of the server to take effect. I would go back over Steps 2 and 3 in the tutorial to make sure you've got it configured correctly.

If you do that and it's still a problem (on at least 1.0.42) then let me know and I'll raise a JIRA ticket to investigate in the next sprint.

Thanks,
Dave

**Comment by boneill** [comment]
Hi David,

I checked and find I am on an earlier release.  I have not had a chance to see if it works on the upgraded version as I ported the changes across to a share archetype project after which it worked fine.  BTW, thanks for these tutorials, I had a go at Aikau a few months back when doco was very thin on the ground and it was hard work.  This makes it much easier to understand, esp compared to whats on the docs.alfresco.com site.  Keep them coming, love this new framework.

Brian

**Comment by draperd** [comment]
No problem, Brian - and thanks for the feedback, it's much appreciated. I'll leave this issue open for now but when you get a chance to try out a later version can you add a comment to let me know if it's resolved the issue.

Many thanks,
Dave

**Comment by draperd** [comment]
There's been no update on this issue for a week so I'm going to close it, but please re-open if the issue has not been resolved adequately.
