### ISSUE TITLE
Incorrect locale sent in Accept-Language header (in IE11)

### ISSUE THREAD

**Issue by AFaust** [Alfresco/Aikau#908]
https://issues.alfresco.com/jira/browse/AKU-612 introduced an attempt to manually derive the "Accept-Language" header from the navigator object. Unforunately, this breaks / overrides the correct Accept-Language header already set by some browsers (like IE11) and may introduce incorrect values.
I.e. my system has been installed in locale de_DE but I usually set the browser content language to just en or de. Regardless of what I set in IE 11, Aikau XHR requests always send de-de in Accept-Language. If I override the getDefaultHeaders in my services to delete the custom-constructed value, the Accept-Language header is set by IE and correct.

As far as I could determine from https://msdn.microsoft.com/en-us/library/ms535867%28v=vs.85%29.aspx there is no property in IE navigator object to determine the correct content language as defined by the user. I would prefer CoreXhr not try to "guess" the header value if the browser is already providing it. Otherwise it should be fixed - the simplest (and most likely to be correct) option seems to be to inject the full Accept-Language header value provided in the initial request to the Aikau page as the default value.

This is using Aikau 1.0.51 on Alfresco 5.0.d

![aikau-xhr-acceptlanguage](https://cloud.githubusercontent.com/assets/2211521/13653541/982b6a7a-e652-11e5-8f36-eafec24e21ab.png)

**Comment by draperd** [comment]
I've raised https://issues.alfresco.com/jira/browse/AKU-885 to address this issue. As this is a bug it will automatically be included in the next sprint, hopefully this will therefore be fixed in the 1.0.60 release.

**Comment by draperd** [comment]
Hopefully you've seen the comments added to the JIRA ticket. I'm not sure how best to resolve this issue as the Accept-Language header is being set appropriately in accordance with the operating system language (if not the browser language). It doesn't appear to be possible to obtain the browser locale via JavaScript (either via `navigator.userLanguage` or `clientInformation.browserLanguage` (which always return the OS language).

The question is how common is this requirement going to be to the typical end user (as opposed to a developer). Our priority is toward not regressing AKU-612 and to ensure optimum performance. The only option to accurately obtain the browser configuration on IE is to fire and a dummy XHR request in order to obtain the Accept Language header set by IE and then use that in the following request.

Unless I can determine that all versions of IE are setting the Accept Language header on POST (the issue reported for AKU-612) in which case we can skip the header setting just for IE (I've not investigated this yet).

**Comment by draperd** [comment]
There's a PR in for this at the moment, and I've put a full description of the solution in the JIRA ticket. This fix should be included in the 1.0.60 release next week.

**Comment by draperd** [comment]
The fix for this is now available in the 1.0.60 release

**Comment by AFaust** [comment]
I have provided a comment on the review ticket https://issues.alfresco.com/jira/browse/AKU-906 that this change has introduced side-effects which may have significant impact on proper page / service initialization.
