### ISSUE TITLE
side effect in Tutorial17

### ISSUE THREAD

**Issue by torstenwerner** [Alfresco/Aikau#938]
Step 5 in Tutorial17 describes a shortcut for displaying the preview. But there is a side effect: documents that needs a transformation for previewing e.g. powerpoint are no longer previewed. A download link is displayed instead. I do not know if it is a bug or the intended behavior of this shortcut.

**Comment by draperd** [comment]
This is the intended behaviour. The transformation is the responsibility of the Alfresco Repository and you need to ensure that your repository is appropriately configured in order to perform transformations (such as MS Office document to PDF in order to be displayed by the PDF.js previewer plugin). The previewer makes the best attempt it can to show a preview based on the renditions available on the node, and if it is not possible to display a preview it will offer the option to download.
